CREATE TABLE IF NOT EXISTS proj1_tables_script23S (
    `DROP_TABLE_grades` VARCHAR(76) CHARACTER SET utf8,
    `Column_2` VARCHAR(46) CHARACTER SET utf8,
    `Column_3` VARCHAR(22) CHARACTER SET utf8,
    `Column_4` VARCHAR(11) CHARACTER SET utf8,
    `Column_5` VARCHAR(13) CHARACTER SET utf8,
    `Column_6` VARCHAR(19) CHARACTER SET utf8,
    `Column_7` VARCHAR(7) CHARACTER SET utf8,
    `Column_8` VARCHAR(5) CHARACTER SET utf8
);
INSERT INTO proj1_tables_script23S VALUES ('DROP TABLE enrollments CASCADE CONSTRAINTS;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('DROP TABLE classes;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('DROP TABLE course_credit;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('DROP TABLE courses CASCADE CONSTRAINTS;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('DROP TABLE students CASCADE CONSTRAINTS;',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE students (',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	sid char(4) PRIMARY KEY CHECK (sid LIKE ''B%'')',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	firstname varchar2(15) NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	lastname varchar2(15) NOT NULL',' ',NULL,NULL,NULL,NULL,NULL,NULL),
	('	status varchar2(10) CHECK (status IN (''freshman''',' ''sophomore''',' ''junior''',' ''senior''',' ''graduate''))',' ',NULL,NULL),
	('	gpa NUMBER(3','2) CHECK (gpa BETWEEN 0 AND 4.0)',NULL,NULL,NULL,NULL,NULL,NULL),
	('	email varchar2(20) UNIQUE',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE courses (',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	dept_code varchar2(4) NOT NULL',' ',NULL,NULL,NULL,NULL,NULL,NULL),
	('	course# number(3) NOT NULL CHECK (course# BETWEEN 100 AND 799)',' ',NULL,NULL,NULL,NULL,NULL,NULL),
	('	title varchar2(20) NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	PRIMARY KEY (dept_code',' course#)',NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE course_credit (',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	course# number(3) NOT NULL primary KEY CHECK (course# BETWEEN 100 AND 799)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	credits number(1) CHECK (credits IN (3',' 4))',NULL,NULL,NULL,NULL,NULL,NULL),
	('	CHECK ((course# < 500 AND credits = 4) OR (course# >= 500 AND credits = 3))',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE classes (',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	classid char(5) PRIMARY KEY CHECK (classid like ''c%'')',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	dept_code varchar2(4) NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	course# number(3) NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	sect# number(2)',' ',NULL,NULL,NULL,NULL,NULL,NULL),
	('	year number(4)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	semester varchar2(6) CHECK (semester IN (''Spring''',' ''Fall''',' ''Summer''))',' ',NULL,NULL,NULL,NULL),
	('	limit number(3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	class_size number(3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	FOREIGN KEY (dept_code',' course#) REFERENCES courses ON DELETE CASCADE',' ',NULL,NULL,NULL,NULL,NULL),
	('	UNIQUE(dept_code',' course#',' sect#',' year',' semester)',NULL,NULL,NULL),
	('	CHECK (class_size <= limit)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE enrollments (',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	sid char(4) REFERENCES students',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	classid char(5) REFERENCES classes',' ',NULL,NULL,NULL,NULL,NULL,NULL),
	('	lgrade char CHECK (lgrade IN (''A''',' ''B''',' ''C''',' ''D''',' ''F''',' ''I''',' NULL))',NULL),
	('	PRIMARY KEY (sid',' classid)',NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE grades(',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	lgrade char CHECK (lgrade IN (''A''',' ''B''',' ''C''',' ''D''',' ''F''',' ''I''',' NULL))',NULL),
	('	ngrade number(1) CHECK (ngrade IN (4',' 3',' 2',' 1',' 0',' NULL))',NULL,NULL),
	('	CHECK ((lgrade = ''A'' AND ngrade = 4) OR (lgrade = ''B'' AND ngrade = 3)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	OR (lgrade = ''C'' AND ngrade = 2) ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	OR (lgrade = ''D'' AND ngrade = 1) ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	OR (lgrade = ''F'' AND ngrade = 0)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	OR (lgrade = ''I'' AND ngrade = NULL)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('	OR (lgrade = NULL AND ngrade = NULL))',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(');',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO students VALUES (''B001''',' ''Anne''',' ''Broder''',' ''junior''',' 3.6',' ''broder@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B002''',' ''Terry''',' ''Buttler''',' ''senior''',' 3.7',' ''buttler@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B003''',' ''Tracy''',' ''Wang''',' ''senior''',' 4.0',' ''wang@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B004''',' ''Barbara''',' ''Callan''',' ''junior''',' 2.5',' ''callan@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B005''',' ''Jack''',' ''Smith''',' ''graduate''',' 3.0',' ''smith@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B006''',' ''Terry''',' ''Zillman''',' ''graduate''',' 4.0',' ''zillman@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B007''',' ''Becky''',' ''Lee''',' ''senior''',' 4.0',' ''lee@bu.edu'');',NULL,NULL),
	('INSERT INTO students VALUES (''B008''',' ''Tom''',' ''Baker''',' ''freshman''',' NULL',' ''baker@bu.edu'');',NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''CS''',' 432',' ''database systems'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''Math''',' 314',' ''discrete math'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''CS''',' 240',' ''data structure'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''Math''',' 221',' ''calculus I'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''CS''',' 532',' ''database systems'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''CS''',' 552',' ''operating systems'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO courses VALUES (''BIOL''',' 425',' ''molecular biology'');',NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (432',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (314',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (240',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (221',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (532',' 3);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (552',' 3);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO course_credit VALUES (425',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO classes VALUES  (''c0001''',' ''CS''',' 432',' 1',' 2022',' ''Spring''',' 35',' 34);'),
	('INSERT INTO classes VALUES  (''c0002''',' ''Math''',' 314',' 1',' 2022',' ''Spring''',' 25',' 24);'),
	('INSERT INTO classes VALUES  (''c0003''',' ''Math''',' 314',' 2',' 2022',' ''Spring''',' 25',' 22);'),
	('INSERT INTO classes VALUES  (''c0004''',' ''CS''',' 432',' 2',' 2022',' ''Spring''',' 30',' 30);'),
	('INSERT INTO classes VALUES  (''c0005''',' ''CS''',' 240',' 1',' 2022',' ''Fall''',' 40',' 39);'),
	('INSERT INTO classes VALUES  (''c0006''',' ''CS''',' 532',' 1',' 2022',' ''Spring''',' 29',' 28);'),
	('INSERT INTO classes VALUES  (''c0007''',' ''Math''',' 221',' 1',' 2022',' ''Spring''',' 30',' 30);'),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B001''',' ''c0001''',' ''A'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B002''',' ''c0002''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B003''',' ''c0004''',' ''A'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B004''',' ''c0004''',' ''C'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B004''',' ''c0005''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B005''',' ''c0006''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B006''',' ''c0006''',' ''A'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B001''',' ''c0002''',' ''C'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B003''',' ''c0005''',' NULL);',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B007''',' ''c0007''',' ''A'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B005''',' ''c0004''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B001''',' ''c0006''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B002''',' ''c0004''',' ''A'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B001''',' ''c0005''',' ''B'');',NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO enrollments VALUES  (''B005''',' ''c0005''',' NULL);',NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''A''',' 4);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''B''',' 3);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''C''',' 2);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''D''',' 1);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''F''',' 0);',NULL,NULL,NULL,NULL,NULL,NULL),
	('INSERT INTO grades VALUES  (''I''',' NULL);',NULL,NULL,NULL,NULL,NULL,NULL);
